---
kind: "operation"
client: "atomist-bot"
generator:
  name: "NewRestService"
  group: "satellite-of-love"
  artifact: "sol-spring-rest-service"
  version: "1.0.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-options.git"
    branch: "master"
    sha: "6cac966"
  parameters:
    - "project_name": "rest-service-generator"
    - "inputParameter": "input"

---
kind: "operation"
client: "rug-cli 0.29.0"
editor:
  name: "ConvertExistingProjectToGenerator"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.24.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "cff978c59d1635572a8de584f1a1daad5e8d7a68"
    sha: "cff978c"
  parameters:
    - "archiveName": "rest-service-generator"
    - "groupId": "satellite-of-love"
    - "version": "1.0.0"
    - "generatorName": "NewRestService"
    - "description": "a standard REST service for satellite-of-love"

