---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "PrepareTravisBuildFiles"
  group: "atomist-rugs"
  artifact: "new-project-rugs"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/new-project-rugs"
    branch: "master"
    sha: "fa1dcfe*"
  parameters:
    - "project": "rest-service-generator"
    - "encryptedGithubToken": "k**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryToken": "l**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryUser": "w**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "PrepareTravisBuildFiles"
  group: "atomist-rugs"
  artifact: "new-project-rugs"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/new-project-rugs"
    branch: "master"
    sha: "fa1dcfe*"
  parameters:
    - "project": "rest-service-generator"
    - "encryptedGithubToken": "S**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryToken": "h**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryUser": "t**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "PrepareTravisBuildFiles"
  group: "atomist-rugs"
  artifact: "new-project-rugs"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/new-project-rugs"
    branch: "master"
    sha: "fa1dcfe*"
  parameters:
    - "project": "rest-service-generator"
    - "encryptedGithubToken": "U**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryToken": "u**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryUser": "f**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "PrepareTravisBuildFiles"
  group: "atomist-rugs"
  artifact: "new-project-rugs"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/new-project-rugs"
    branch: "master"
    sha: "fa1dcfe*"
  parameters:
    - "project": "rest-service-generator"
    - "encryptedGithubToken": "t**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryToken": "M**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryUser": "g**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "PrepareTravisBuildFiles"
  group: "satellite-of-love"
  artifact: "new-project-rugs"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/new-project-rugs"
    branch: "master"
    sha: "fa1dcfe*"
  parameters:
    - "project": "rest-service-generator"
    - "encryptedGithubToken": "R**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryToken": "w**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryUser": "w**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "PrepareTravisBuildFiles"
  group: "satellite-of-love"
  artifact: "new-project-rugs"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/new-project-rugs"
    branch: "master"
    sha: "fa1dcfe*"
  parameters:
    - "project": "rest-service-generator"
    - "encryptedGithubToken": "f**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryToken": "f**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryUser": "h**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "AddLocalEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.25.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "7557a1b"
  parameters:
    - "editorName": "BumpVersion"
    - "description": "bump the version of this rug archive"
    - "groupId": "satellite-of-love"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.10.0"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "203577f"
  parameters:
    - "component": "minor"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "AddLocalEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.25.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "7557a1b"
  parameters:
    - "editorName": "AddRestEndpoint"
    - "description": "add an endpoint to return a POJO"
    - "groupId": "satellite-of-love"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.0"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "60065c7"
  parameters:
    - "component": "patch"

