dist: trusty
sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /^v?\d+\.\d+\.\d+/
install: true
script: docker login -u $ATOMIST_REPO_USER -p $ATOMIST_REPO_TOKEN $ATOMIST_DOCKER_REGISTRY
  && bash src/main/scripts/travis-build.bash
env:
  global:
  - secure: wsr6DYdrUaO+9pibgE32Se/9SIynSXizQUtjnQJadaPoW0vTGKwz4vpddo9FxuFdB1kwhbaQ7W3aoWEdX+mpP8XcpA/Jqu6sfb+2FxDcDFcDTmTwF5HYI0fXuOF8xB67FVMVO0jHOZpzX1rwBE226Omt8SDSk761raGoKD50lF9AzqXKl4hSe3jOZAi5UcizZLJHEkkc7ByEJoed//OK86rfzADSmRVajAXOaB5iFgjtldApXjpxOmn9FaNMZ27K9SlAJTXihFnFUmSs9ke+92s0H9k0ZkuFUgSrL4474IM8pBokupM2qzlSU2mPzhP/WrePCQfoyEnkywHdXHFbASTGi7zFBQtpwUXdoPW7HHisdVNJzgzWbTihnYHnQq+/aWkz3+IXt5hMX1AZfn8DXoN3qx+iPySmf8RaQA+6drzUr0byKRmLQZ9AW7aAekaI3lnVoP6hpLQv34pha9t1yRPH4G1qvxwz81NAg65CUoE4gRmmF/MMHGxSC6INjLpejcKGVokRJG8C2ZTkZx8PcJ1HPfyKWwkvbp+DFQ1mm6htUhXB9WrszAQoDmL/jW1WCZ9X3n44P53/LPDXs97oaWlv3g3eJ2NZQv8+qlcqP5bvTaWKGTrqDh4HNzWhES1rRTYM6r4q8HNf02ZZHW/jb7WmYh2EPp9HmxIV9TqkrPQ=
  - secure: wxh3NNYeeZe6eGU2oM6/hiKrt/UA+URN7OUlw3jnauEYfLtwU7HFnzS+YWcoEqeH/TKLGvAWNxYbAVmmcEjrV6elY6RS+MScveMZhDBAL8hn9eHoIRUSQ7bFk++DbgIm19OfbzDuQ8SOH6zyIAMKGjXlvBEiozgXH+Bz4a9D84a7kVHlgZYc0N6QAFCQ3Yfxw9DWDnq0MdVBFenTQ+6hnzBflfhim8zZ51NDsXSX8TenxHvULK2DE3sDUMDzNdX4LIIJh01U3BjvSb6yCxOyIKoYwz3UrE1oRLZiwif3mDfKaStinAqS5H/bqjY91eA413+NUz/8kpOPxVH/fih6Z8WVCj79H2/6B3JQEFVscI7jOOQmBNxjZl8cobObFa8lk1CFIX8pi3adMNYzXcWOz+Bifmd3udFbeH45Mxvh4tmlE2pfyOgcXj4MyA6Ju56mGsJ3i8JgJCvtb4ymEtZDo35lWohwDoBdgLjYcfx33Y+ItA8X3NXjhG2Jee7Qz7xwaC3WImkiSPXyiBPYqwK0C/Rp334EJiJHQ12SGklXC9Fx14IY0zIioNNQIZA6AGHKLpxwwySfRYYN4HGYatzHBd/5MdQu156Lu6Y6UnJUKpMn0Ay3U+HeX4Sz1p2Zq3A+y2KF6hNXhudsGrHl3ktP2kTRda+gseb8zKgw920nNVM=
  - secure: R9OsKJzcMMJPcBaZm1lusk+fzZ9ukuf/ERbzx9bdz6Yqu4dfs9ZJ6EGnQDjumBzxNxdGk1iqFwNUn4tPw9BoryR8P90KNOwkHDsCt6SCpHR9iE0hfqXqLQKWLHNkcXIyP/psauAQypmIbfddyT08IXl1K7xMgVGcC7IqhGy1kZn7yfUejkFfhCivLDvy1hYORwpyi3AHq+dnVZF52H3qTNevDcX9rPjOZcayzNt7jeh6e8YVgzJH/NDpOoZkXz6tR+PZSO69oX96iYckiepnRF7Lvsqm+vB4JYQcm8u6T+x0fy7sJ9DRhGY9djQJtPAApVeIjO7D9D31VXM7PVMmZh8AcqSzsIV57X0ZH+ieh7wuZZLh+y+aWN16nC4TjrtuOcYpktwq0t5qeN3Kqhm+zkOcDDgiR+bUSTaSQvDP5uFuNTm6MAnDCodSTlserSNkYWuCFfCYc9hwdO6sQsmICBiK55+DO/w1MIGp2UUDaGttCQHWX4WZwh3oQwU68kHX4xdoeamK8Lqji2g1PiY4IMssrIV7zwC9st0muGeT6BAXE9QKme1wT5vZPouUHau/+fzaL5VGZ0uJe4A87v6vCBIfdEaUPK5x9CBE0k2Z6dhEhQW1SfeBMlQtJQ1lYvBDB/KOtPMwQ/6x7cwN/6Bu+zU9c9+j7qZa+thH7/amX2o=
  - ATOMIST_DOCKER_REGISTRY=sforzando-docker-dockerv2-local.artifactoryonline.com
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
