Feature: Tests from AddRestEndpoint.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.




  Scenario: AddRestEndpoint is added to your project by AddAddRestEndpoint
    Given the archive root
    When AddRestEndpoint inputParameteristhe inputParameter value for AddRestEndpoint is added to your project by AddAddRestEndpoint
    Then parameters were valid
    Then changes were made
    Then fileContains hello txt Hello Worldnot for AddRestEndpoint is added to your project by AddAddRestEndpoint
