Feature: Tests from BumpVersion.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.




  Scenario: BumpVersion is added to your project by AddBumpVersion
    Given the archive root
    When BumpVersion inputParameteristhe inputParameter value for BumpVersion is added to your project by AddBumpVersion
    Then parameters were valid
    Then changes were made
    Then fileContains hello txt Hello Worldnot for BumpVersion is added to your project by AddBumpVersion
