Feature: Tests from RestrictCORS.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.




  Scenario: RestrictCORS is added to your project by AddRestrictCORS
    Given the archive root
    When RestrictCORS inputParameteristhe inputParameter value for RestrictCORS is added to your project by AddRestrictCORS
    Then parameters were valid
    Then changes were made
    Then fileContains hello txt Hello Worldnot for RestrictCORS is added to your project by AddRestrictCORS
