Feature: Tests from UpgradeDockerfile.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.




  Scenario: UpgradeDockerfile is added to your project by AddUpgradeDockerfile
    Given the archive root
    When UpgradeDockerfile inputParameteristhe inputParameter value for UpgradeDockerfile is added to your project by AddUpgradeDockerfile
    Then parameters were valid
    Then changes were made
    Then fileContains hello txt Hello Worldnot for UpgradeDockerfile is added to your project by AddUpgradeDockerfile
